# .cargo/config.toml
[build]
# Enable parallel compilation
codegen-units = 16

# Enable link-time optimization in release mode
[profile.release]
lto = "thin"
codegen-units = 1
strip = true  # Strip symbols from the binary

# Use the faster Mold linker on supported platforms
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/zld"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld"

